apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: kg-experiments
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi
