apiVersion: v1
kind: Secret
metadata:
  name: kg-secrets
  namespace: kg-experiments
type: Opaque
stringData:
  NEO4J_URI: "neo4j+s://placeholder"
  NEO4J_PASSWORD: "placeholder"
  MLFLOW_TRACKING_URI: "https://dagshub.com/placeholder"
  MLFLOW_TRACKING_TOKEN: "placeholder"
  HF_TOKEN: "hf_placeholder"
