apiVersion: v1
kind: Pod
metadata:
  name: storage-test
  namespace: kg-experiments
spec:
  containers:
  - name: shell
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: cache
      mountPath: /cache
  volumes:
  - name: cache
    persistentVolumeClaim:
      claimName: model-cache
